services:
  capgo-server:
    build: ./server
    container_name: capgo-server
    restart: unless-stopped
    environment:
      - BASE_URL=https://capgo.abrane.ir
      - WATCHTOWER_KEY=${WATCHTOWER_KEY:-}
      - WATCHTOWER_URL=${WATCHTOWER_URL:-}
    volumes:
      - capgo-data:/app/pb_data
    networks:
      - app
      - caddy

  capgo-admin:
    build: ./admin
    container_name: capgo-admin
    restart: unless-stopped
    environment:
      - VITE_PB_URL=https://capgo.abrane.ir
    networks:
      - app
      - caddy

volumes:
  capgo-data:

networks:
  app:
  caddy:
    external: true
    name: caddy-net
